global.constants = {
    token:'GDAqqvfcRKUTnvnvQXPnLY_1H2Issyuwit1mvE54:8pmrSLujRtXPWzEap23pWfAljnY=:eyJzY29wZSI6ImJpc2hlIiwicmV0dXJuQm9keSI6IntcImtleVwiOlwiJChrZXkpXCIsXCJoYXNoXCI6XCIkKGV0YWcpXCIsXCJidWNrZXRcIjpcIiQoYnVja2V0KVwiLFwiZnNpemVcIjokKGZzaXplKSxcImZuYW1lXCI6JChmbmFtZSksXCJlbmRVc2VyXCI6JChlbmRVc2VyKX0iLCJkZWFkbGluZSI6MTU0NzExMTQ4OX0='
};